# Buildpack API version
api = "0.9"

# Buildpack ID and metadata
[buildpack]
id = "showpune/export-buildresult"
version = "0.0.1"
name = "copy build result Buildpack"
homepage = "https://github.com/showpune/export-buildresult"

[[stacks]]
  id = "*"